import { LutPreset, GradingState } from '../types/lut';
import { DEFAULT_GRADING_STATE } from './colorScience';

export const BASIC_STARTER_LUTS: LutPreset[] = [
  {
    id: 'basic-contrast-boost',
    name: 'Creștere Contrast (High Contrast)',
    category: 'creative',
    description: 'Accentuarea gamei dinamice cu o curbă S cinematografică, negru adânc și lumini protejate. Punct de plecare ideal pentru imagini plate.',
    previewColor: '#3b82f6',
    state: {
      contrast: 1.35,
      pivot: 0.435,
      shadows: -14,
      highlights: -8,
      blacks: -6,
      whites: 4,
      saturation: 1.08,
      colorBoost: 6,
      masterCurve: [
        { x: 0, y: 0.01 },
        { x: 0.22, y: 0.14 },
        { x: 0.5, y: 0.5 },
        { x: 0.78, y: 0.86 },
        { x: 1, y: 0.99 },
      ],
      lutTitle: 'Basic_Contrast_Boost',
      lutDescription: 'Punct de pornire cu contrast ridicat si curba S pentru DaVinci Resolve',
    },
  },
  {
    id: 'basic-warm-white-balance',
    name: 'Balans de Alb Cald (Warm Golden)',
    category: 'creative',
    description: 'Transformă imaginile reci sau sterile într-o atmosferă caldă de apus sau lumină incandescentă (temperatura +28, nuanțe aurii în gain).',
    previewColor: '#f59e0b',
    state: {
      temperature: 28,
      tint: -3,
      contrast: 1.08,
      saturation: 1.06,
      colorBoost: 8,
      gain: { r: 1.09, g: 1.03, b: 0.91 },
      gainMaster: 1.01,
      gamma: { r: 0.03, g: 0.01, b: -0.04 },
      highlightTint: { r: 0.2, g: 0.1, b: -0.1 },
      highlightTintStrength: 20,
      lutTitle: 'Basic_Warm_Balance',
      lutDescription: 'Balans de alb cald auriu pentru DaVinci Resolve Studio',
    },
  },
  {
    id: 'basic-cool-white-balance',
    name: 'Balans de Alb Rece (Cool Cyan)',
    category: 'creative',
    description: 'Răcește cadrul cu o nuanță cian-albastră modernă, ideală pentru cadre nocturne, corporative sau atmosferă nordică rece.',
    previewColor: '#06b6d4',
    state: {
      temperature: -26,
      tint: -2,
      contrast: 1.12,
      saturation: 0.96,
      gain: { r: 0.91, g: 0.98, b: 1.12 },
      gainMaster: 1.0,
      lift: { r: -0.03, g: 0.01, b: 0.05 },
      shadowTint: { r: -0.15, g: 0.05, b: 0.2 },
      shadowTintStrength: 22,
      lutTitle: 'Basic_Cool_Balance',
      lutDescription: 'Balans de alb rece cinematografic pentru DaVinci Resolve Studio',
    },
  },
  {
    id: 'basic-sepia-tone',
    name: 'Efect Sepia Clasic (Antique Sepia)',
    category: 'vintage',
    description: 'Desaturare elegantă cu viraj cald autentic de sepia (nuanțe bogate de ciocolată și hârtie fotografică veche)',
    previewColor: '#b45309',
    state: {
      saturation: 0.05,
      colorBoost: -90,
      contrast: 1.18,
      pivot: 0.45,
      temperature: 15,
      shadows: 6,
      blacks: 4,
      shadowTint: { r: 0.26, g: 0.14, b: -0.05 },
      shadowTintStrength: 55,
      highlightTint: { r: 0.32, g: 0.22, b: 0.04 },
      highlightTintStrength: 45,
      splitBalance: -5,
      lift: { r: 0.04, g: 0.02, b: -0.01 },
      gain: { r: 1.08, g: 1.03, b: 0.9 },
      masterCurve: [
        { x: 0, y: 0.04 },
        { x: 0.25, y: 0.22 },
        { x: 0.75, y: 0.78 },
        { x: 1, y: 0.96 },
      ],
      lutTitle: 'Basic_Sepia_Antique',
      lutDescription: 'Viraj Sepia clasic cu contrast de hartie vintage',
    },
  },
  {
    id: 'basic-vintage-film',
    name: 'Stil Vintage Retro (Matte 70s Film)',
    category: 'vintage',
    description: 'Look nostalgic de peliculă analogică cu negru ridicat (matte shadows), contrast cald și tonuri aurii-verzulii retro.',
    previewColor: '#d97706',
    state: {
      contrast: 1.14,
      pivot: 0.42,
      blacks: 8,
      shadows: 12,
      highlights: -14,
      temperature: 12,
      tint: 4,
      saturation: 1.1,
      colorBoost: 10,
      lift: { r: 0.04, g: 0.03, b: -0.02 },
      liftMaster: 0.04,
      gain: { r: 1.06, g: 1.04, b: 0.92 },
      masterCurve: [
        { x: 0, y: 0.07 },
        { x: 0.3, y: 0.32 },
        { x: 0.7, y: 0.72 },
        { x: 1, y: 0.95 },
      ],
      shadowTint: { r: 0.1, g: 0.12, b: -0.05 },
      shadowTintStrength: 25,
      hueVsSat: { red: 15, yellow: 12, green: -10, cyan: -15, blue: -20, magenta: 0 },
      lutTitle: 'Basic_Vintage_Retro',
      lutDescription: 'Stil vintage analogic cu negru mat pentru DaVinci Resolve',
    },
  },
];

export const CINEMA_PRESETS: LutPreset[] = [
  ...BASIC_STARTER_LUTS,
  {
    id: 'kodak-2383',
    name: 'Kodak 2383 Print Film',
    category: 'cinema',
    description: 'Etalonul industriei cinematografice de la Hollywood (Dune, Oppenheimer, Top Gun). Umbre cian adânci și tonuri calde de piele.',
    previewColor: '#e07a3c',
    state: {
      contrast: 1.25,
      pivot: 0.44,
      saturation: 1.15,
      colorBoost: 12,
      temperature: 6,
      tint: -2,
      shadows: -10,
      highlights: -14,
      blacks: -4,
      whites: 2,
      lift: { r: -0.06, g: 0.02, b: 0.08 },
      liftMaster: -0.04,
      gamma: { r: 0.04, g: -0.01, b: -0.05 },
      gammaMaster: 0.02,
      gain: { r: 1.08, g: 1.02, b: 0.92 },
      gainMaster: 1.02,
      shadowTint: { r: -0.2, g: 0.05, b: 0.3 },
      shadowTintStrength: 35,
      highlightTint: { r: 0.25, g: 0.12, b: -0.15 },
      highlightTintStrength: 25,
      splitBalance: -10,
      masterCurve: [
        { x: 0, y: 0.02 },
        { x: 0.22, y: 0.16 },
        { x: 0.52, y: 0.54 },
        { x: 0.8, y: 0.84 },
        { x: 1, y: 0.98 },
      ],
      redCurve: [
        { x: 0, y: 0 },
        { x: 0.5, y: 0.53 },
        { x: 1, y: 1 },
      ],
      blueCurve: [
        { x: 0, y: 0.03 },
        { x: 0.5, y: 0.47 },
        { x: 1, y: 0.94 },
      ],
      hueVsSat: { red: 10, yellow: -5, green: -15, cyan: 20, blue: 15, magenta: -10 },
      hueVsHue: { red: 4, yellow: -4, green: 8, cyan: -6, blue: -8, magenta: 0 },
      lutTitle: 'Kodak_2383_Print_Film',
      lutDescription: 'Emulare film print 35mm pentru DaVinci Resolve',
    },
  },
  {
    id: 'kodak-vision3-5207',
    name: 'Kodak Vision3 250D',
    category: 'cinema',
    description: 'Negativ cinematografic de 35mm cu tranziție organică catifelată a luminilor și redare fidelă a tenului uman.',
    previewColor: '#eab308',
    state: {
      contrast: 1.12,
      pivot: 0.42,
      saturation: 1.08,
      colorBoost: 8,
      temperature: 8,
      tint: 1,
      highlights: -18,
      shadows: 6,
      lift: { r: 0.01, g: 0.01, b: 0.02 },
      liftMaster: 0.01,
      gamma: { r: 0.03, g: 0.01, b: -0.02 },
      gammaMaster: 0.01,
      gain: { r: 1.05, g: 1.01, b: 0.95 },
      gainMaster: 1.0,
      masterCurve: [
        { x: 0, y: 0.03 },
        { x: 0.25, y: 0.22 },
        { x: 0.75, y: 0.76 },
        { x: 1, y: 0.96 },
      ],
      hueVsSat: { red: 8, yellow: 4, green: -10, cyan: 0, blue: -5, magenta: -5 },
      lutTitle: 'Kodak_Vision3_250D',
      lutDescription: 'Emulare negativ Kodak Vision3 pentru DaVinci Resolve',
    },
  },
  {
    id: 'teal-and-orange',
    name: 'Blockbuster Teal & Orange',
    category: 'cinema',
    description: 'Separare cromatică de Hollywood: nuanțe calde saturate pe ten și tonuri reci cian-albastre în fundal și cer.',
    previewColor: '#0ea5e9',
    state: {
      contrast: 1.28,
      pivot: 0.45,
      saturation: 1.22,
      colorBoost: 18,
      temperature: 4,
      tint: -6,
      shadows: -12,
      highlights: 4,
      blacks: -6,
      lift: { r: -0.15, g: 0.02, b: 0.22 },
      liftMaster: -0.05,
      gamma: { r: 0.05, g: -0.02, b: -0.08 },
      gammaMaster: 0.01,
      gain: { r: 1.15, g: 1.02, b: 0.84 },
      gainMaster: 1.04,
      shadowTint: { r: -0.3, g: 0.1, b: 0.4 },
      shadowTintStrength: 45,
      highlightTint: { r: 0.35, g: 0.15, b: -0.2 },
      highlightTintStrength: 35,
      splitBalance: -5,
      hueVsHue: { red: 8, yellow: -10, green: 25, cyan: -12, blue: -15, magenta: 0 },
      hueVsSat: { red: 20, yellow: 15, green: -25, cyan: 30, blue: 25, magenta: -20 },
      lutTitle: 'Hollywood_Teal_Orange',
      lutDescription: 'Look comercial Blockbuster pentru DaVinci Resolve',
    },
  },
  {
    id: 'fuji-eterna',
    name: 'Fujifilm Eterna 8543',
    category: 'cinema',
    description: 'Peliculă japoneză discretă cu contrast redus, nuanțe pastelate și o textură poetică favorită filmelor de autor.',
    previewColor: '#10b981',
    state: {
      contrast: 0.94,
      pivot: 0.42,
      saturation: 0.88,
      colorBoost: -5,
      temperature: -4,
      tint: -2,
      shadows: 14,
      highlights: -12,
      lift: { r: -0.02, g: 0.03, b: 0.04 },
      liftMaster: 0.03,
      gamma: { r: -0.01, g: 0.02, b: 0.01 },
      gammaMaster: 0.02,
      gain: { r: 0.97, g: 1.02, b: 1.0 },
      gainMaster: 0.98,
      masterCurve: [
        { x: 0, y: 0.05 },
        { x: 0.3, y: 0.32 },
        { x: 0.7, y: 0.69 },
        { x: 1, y: 0.94 },
      ],
      hueVsSat: { red: -8, yellow: -12, green: 5, cyan: 10, blue: -10, magenta: -15 },
      lutTitle: 'Fuji_Eterna_8543',
      lutDescription: 'Emulare Fuji Eterna film stock pentru DaVinci Resolve',
    },
  },
  {
    id: 'bleach-bypass',
    name: 'Bleach Bypass (Reținere Argint)',
    category: 'creative',
    description: 'Stil industrial aspru desaturat, contrast extrem și luciu metalic (Saving Private Ryan, Se7en, Fight Club).',
    previewColor: '#94a3b8',
    state: {
      contrast: 1.48,
      pivot: 0.48,
      saturation: 0.52,
      colorBoost: -25,
      shadows: -20,
      highlights: 16,
      blacks: -12,
      whites: 10,
      lift: { r: -0.05, g: -0.04, b: -0.03 },
      liftMaster: -0.08,
      gain: { r: 1.1, g: 1.08, b: 1.05 },
      gainMaster: 1.08,
      masterCurve: [
        { x: 0, y: 0 },
        { x: 0.25, y: 0.14 },
        { x: 0.75, y: 0.88 },
        { x: 1, y: 1 },
      ],
      hueVsSat: { red: 5, yellow: -40, green: -50, cyan: -20, blue: -20, magenta: -30 },
      lutTitle: 'Bleach_Bypass_Silver',
      lutDescription: 'Efect Bleach Bypass pelicula argintata',
    },
  },
  {
    id: 'ilford-hp5-mono',
    name: 'Ilford HP5 Alb-Negru Argintiu',
    category: 'monochrome',
    description: 'Pasiune alb-negru analogică pură, cu contrast definit pe tonurile medii și gradație nobilă a umbrelor.',
    previewColor: '#cbd5e1',
    state: {
      contrast: 1.28,
      pivot: 0.46,
      saturation: 0.0,
      colorBoost: -100,
      shadows: -8,
      highlights: -10,
      blacks: -4,
      whites: 6,
      masterCurve: [
        { x: 0, y: 0.01 },
        { x: 0.22, y: 0.16 },
        { x: 0.5, y: 0.52 },
        { x: 0.78, y: 0.82 },
        { x: 1, y: 0.99 },
      ],
      lutTitle: 'Ilford_HP5_Monochrome',
      lutDescription: 'Alb-negru analogic de calitate pentru DaVinci Resolve',
    },
  },
  {
    id: 'slog3-to-rec709-cine',
    name: 'Sony S-Log3 → Rec.709 Cine',
    category: 'log_conversion',
    description: 'Transformă profilul plat Sony S-Log3 în culori Rec.709 vibrante, cu roll-off de peliculă și protecție a tenului.',
    previewColor: '#38bdf8',
    state: {
      inputSpace: 'slog3',
      contrast: 1.16,
      pivot: 0.435,
      saturation: 1.12,
      colorBoost: 10,
      temperature: 2,
      shadows: -4,
      highlights: -10,
      gain: { r: 1.04, g: 1.01, b: 0.98 },
      lutTitle: 'Sony_SLog3_to_Rec709',
      lutDescription: 'Conversie S-Log3 la Rec.709 pentru DaVinci Resolve Studio',
    },
  },
  {
    id: 'logc3-to-rec709-alexa',
    name: 'ARRI LogC3 → Rec.709 Cine Alexa',
    category: 'log_conversion',
    description: 'Standardul de aur ARRI Alexa: tranziție naturală a luminilor și profunzime organică a culorii.',
    previewColor: '#a855f7',
    state: {
      inputSpace: 'logc3',
      contrast: 1.1,
      pivot: 0.42,
      saturation: 1.06,
      colorBoost: 6,
      temperature: 3,
      shadows: 2,
      highlights: -14,
      gain: { r: 1.02, g: 1.0, b: 0.98 },
      lutTitle: 'ARRI_LogC3_to_Rec709',
      lutDescription: 'Conversie ARRI LogC3 la Rec.709 pentru DaVinci Resolve Studio',
    },
  },
  // ==========================================
  // STILURI DE NUNTĂ (WEDDING LOOKS)
  // ==========================================
  {
    id: 'wedding-nature-outdoor',
    name: 'Nuntă în Natură (Cununie / Golden Hour)',
    category: 'wedding',
    description: 'Stil romantic diafan pentru ceremonii în aer liber și ședințe foto: verdeață organică temperată (fără verde acid), ten cald de piersică și alb protejat pe rochie.',
    previewColor: '#10b981',
    state: {
      contrast: 1.12,
      pivot: 0.435,
      temperature: 8,
      tint: 1,
      saturation: 1.06,
      colorBoost: 14,
      highlights: -18,
      whites: -5,
      shadows: 6,
      blacks: 2,
      gain: { r: 1.05, g: 1.02, b: 0.96 },
      gainMaster: 1.01,
      gamma: { r: 0.02, g: 0.01, b: -0.02 },
      hueVsHue: { red: 2, yellow: -4, green: 14, cyan: -4, blue: 0, magenta: 0 },
      hueVsSat: { red: 8, yellow: 6, green: -28, cyan: -10, blue: -5, magenta: -5 },
      hueVsLum: { red: 5, yellow: 8, green: -10, cyan: 0, blue: 0, magenta: 0 },
      masterCurve: [
        { x: 0, y: 0.02 },
        { x: 0.25, y: 0.23 },
        { x: 0.75, y: 0.78 },
        { x: 1, y: 0.97 },
      ],
      lutTitle: 'Wedding_Nature_Golden',
      lutDescription: 'Stil nunta in natura cu verdeata temperata si ten cald pentru DaVinci Resolve',
    },
  },
  {
    id: 'wedding-dancefloor-led',
    name: 'Sală de Dans Luminată LED (Party & Lasere)',
    category: 'wedding',
    description: 'Corecție specială pentru ringul de dans cu lumini DJ LED agresive: calmează exploziile de magenta și albastru fluorescent, protejând tenul mirilor împotriva arsurilor de culoare.',
    previewColor: '#8b5cf6',
    state: {
      contrast: 1.24,
      pivot: 0.44,
      temperature: -2,
      tint: -4,
      saturation: 1.04,
      colorBoost: 10,
      highlights: -24,
      whites: -8,
      shadows: -10,
      blacks: -4,
      lift: { r: -0.02, g: 0.0, b: 0.02 },
      gamma: { r: 0.04, g: 0.01, b: -0.03 },
      gain: { r: 1.02, g: 0.98, b: 0.94 },
      gainMaster: 0.99,
      hueVsSat: { red: 4, yellow: 8, green: -15, cyan: -20, blue: -25, magenta: -35 },
      hueVsLum: { red: 6, yellow: 10, green: 0, cyan: -10, blue: -15, magenta: -20 },
      shadowTint: { r: -0.08, g: 0.02, b: 0.12 },
      shadowTintStrength: 18,
      lutTitle: 'Wedding_Dancefloor_LED',
      lutDescription: 'Protectie ten si rochie sub lumini DJ LED pentru DaVinci Resolve',
    },
  },
  {
    id: 'wedding-architectural-lights',
    name: 'Sală de Dans cu Lumini Arhitecturale (Uplighting)',
    category: 'wedding',
    description: 'Atmosferă nobilă de bal și banchet iluminat cu proiectoare arhitecturale calde (amber/chihlimbariu): negru profund pentru costume, rochie albă perlată și fețe fără viraj gălbui.',
    previewColor: '#f59e0b',
    state: {
      contrast: 1.18,
      pivot: 0.435,
      temperature: 6,
      tint: -3,
      saturation: 1.08,
      colorBoost: 12,
      highlights: -14,
      whites: -2,
      shadows: -4,
      blacks: -2,
      gain: { r: 1.08, g: 1.03, b: 0.92 },
      gainMaster: 1.01,
      gamma: { r: 0.03, g: -0.01, b: -0.03 },
      shadowTint: { r: 0.14, g: 0.08, b: -0.04 },
      shadowTintStrength: 25,
      highlightTint: { r: 0.18, g: 0.12, b: -0.06 },
      highlightTintStrength: 18,
      hueVsHue: { red: 4, yellow: -6, green: 8, cyan: -4, blue: -6, magenta: 2 },
      hueVsSat: { red: 12, yellow: -8, green: -15, cyan: 10, blue: 12, magenta: -5 },
      lutTitle: 'Wedding_Architectural_Hall',
      lutDescription: 'Lumini arhitecturale si candelabre calde pentru DaVinci Resolve',
    },
  },
  {
    id: 'wedding-boho-terracotta',
    name: 'Nuntă Boho Warm & Terracotta',
    category: 'wedding',
    description: 'Look contemporan boho-chic: iarbă de pampas, tonuri calde pământii de teracotă, verdeață desaturată măsliniu și ten catifelat auriu.',
    previewColor: '#d97706',
    state: {
      contrast: 1.13,
      pivot: 0.43,
      temperature: 12,
      tint: 3,
      saturation: 1.05,
      colorBoost: 16,
      highlights: -16,
      whites: -4,
      shadows: 8,
      blacks: 4,
      lift: { r: 0.03, g: 0.01, b: -0.02 },
      gain: { r: 1.09, g: 1.03, b: 0.90 },
      hueVsHue: { red: 4, yellow: -8, green: 18, cyan: -6, blue: -4, magenta: 4 },
      hueVsSat: { red: 14, yellow: 12, green: -34, cyan: -15, blue: -12, magenta: -10 },
      hueVsLum: { red: 8, yellow: 10, green: -12, cyan: 0, blue: 0, magenta: 0 },
      shadowTint: { r: 0.12, g: 0.08, b: -0.04 },
      shadowTintStrength: 22,
      lutTitle: 'Wedding_Boho_Terracotta',
      lutDescription: 'Stil Boho cald cu pampas si tonuri pamantii pentru DaVinci Resolve',
    },
  },
  {
    id: 'wedding-light-airy',
    name: 'Nuntă Light & Airy (Fine Art Pastel)',
    category: 'wedding',
    description: 'Estetică diafană de vilă europeană: lumini deschise mătăsoase, contrast blând, rochie albă perlată și nuanțe pastelate romantice.',
    previewColor: '#38bdf8',
    state: {
      contrast: 1.04,
      pivot: 0.42,
      temperature: 2,
      tint: 1,
      saturation: 1.02,
      colorBoost: 8,
      highlights: -10,
      whites: 2,
      shadows: 18,
      blacks: 6,
      lift: { r: 0.02, g: 0.02, b: 0.03 },
      gain: { r: 1.02, g: 1.02, b: 1.01 },
      gainMaster: 1.03,
      masterCurve: [
        { x: 0, y: 0.06 },
        { x: 0.35, y: 0.39 },
        { x: 0.75, y: 0.81 },
        { x: 1, y: 0.98 },
      ],
      hueVsSat: { red: 6, yellow: 4, green: -22, cyan: 8, blue: 6, magenta: 0 },
      lutTitle: 'Wedding_Light_Airy',
      lutDescription: 'Stil luminos pastelat Fine Art pentru DaVinci Resolve',
    },
  },
  {
    id: 'wedding-moody-romantic',
    name: 'Nuntă Moody & Dark Romantic (Emerald)',
    category: 'wedding',
    description: 'Atmosferă cinematografică intimă și misterioasă: umbre adânci, verde smarald profund de pădure, lumini calde de lumânări și contrast nobil.',
    previewColor: '#059669',
    state: {
      contrast: 1.25,
      pivot: 0.44,
      temperature: 4,
      tint: -2,
      saturation: 0.96,
      colorBoost: 12,
      highlights: -18,
      whites: -6,
      shadows: -16,
      blacks: 2,
      lift: { r: -0.03, g: -0.01, b: 0.02 },
      gamma: { r: 0.02, g: -0.01, b: -0.03 },
      gain: { r: 1.04, g: 1.01, b: 0.93 },
      shadowTint: { r: -0.04, g: 0.06, b: 0.08 },
      shadowTintStrength: 24,
      hueVsHue: { red: 2, yellow: -6, green: -12, cyan: 4, blue: 0, magenta: 0 },
      hueVsSat: { red: 10, yellow: -4, green: -18, cyan: -10, blue: -15, magenta: -20 },
      hueVsLum: { red: 6, yellow: 4, green: -22, cyan: -8, blue: -10, magenta: -10 },
      lutTitle: 'Wedding_Moody_Romantic',
      lutDescription: 'Stil moody romantic cu verde smarald pentru DaVinci Resolve',
    },
  },
  {
    id: 'wedding-sunset-tuscan',
    name: 'Nuntă Apus Toscan (Golden Honey Sunset)',
    category: 'wedding',
    description: 'Apus spectaculos de soare: nuanțe bogate de miere și chihlimbariu pe fețe, radiație solară caldă și contrast fin pe rochie.',
    previewColor: '#eab308',
    state: {
      contrast: 1.15,
      pivot: 0.435,
      temperature: 16,
      tint: 1,
      saturation: 1.10,
      colorBoost: 18,
      highlights: -20,
      whites: -5,
      shadows: 4,
      blacks: -2,
      gain: { r: 1.12, g: 1.04, b: 0.88 },
      gainMaster: 1.02,
      gamma: { r: 0.03, g: 0.02, b: -0.03 },
      highlightTint: { r: 0.25, g: 0.15, b: -0.12 },
      highlightTintStrength: 24,
      hueVsSat: { red: 16, yellow: 14, green: -26, cyan: -12, blue: 8, magenta: 0 },
      lutTitle: 'Wedding_Tuscan_Sunset',
      lutDescription: 'Apus cald cu nuante de miere pentru DaVinci Resolve',
    },
  },
  {
    id: 'wedding-kodak-portra',
    name: 'Nuntă Kodak Portra 400 (Pelicula Clasică)',
    category: 'wedding',
    description: 'Etalonul mondial al fotografiei și cinematografiei de nuntă pe film: tonuri pastelate de piersică pe ten, lumini catifelate și tranziții mătăsoase pe alb.',
    previewColor: '#fb923c',
    state: {
      contrast: 1.11,
      pivot: 0.43,
      temperature: 6,
      tint: 2,
      saturation: 1.08,
      colorBoost: 14,
      highlights: -15,
      whites: -3,
      shadows: 4,
      blacks: 2,
      lift: { r: 0.01, g: 0.0, b: -0.01 },
      gamma: { r: 0.02, g: 0.01, b: -0.02 },
      gain: { r: 1.05, g: 1.02, b: 0.95 },
      hueVsHue: { red: 2, yellow: -4, green: 8, cyan: -2, blue: -2, magenta: 2 },
      hueVsSat: { red: 14, yellow: 10, green: -20, cyan: 6, blue: 4, magenta: -4 },
      lutTitle: 'Wedding_Kodak_Portra_400',
      lutDescription: 'Emulare pelicula Kodak Portra 400 pentru nunti in DaVinci Resolve',
    },
  },
  {
    id: 'wedding-retro-super8',
    name: 'Nuntă Retro Super 8 / 16mm Nostalgia',
    category: 'wedding',
    description: 'Amintiri de familie pe peliculă de epocă: umbre mate ridicate, căldură sepia discretă în negru și culori organice nostalgice.',
    previewColor: '#b45309',
    state: {
      contrast: 1.12,
      pivot: 0.42,
      temperature: 14,
      tint: 4,
      saturation: 0.98,
      colorBoost: 8,
      highlights: -18,
      shadows: 14,
      blacks: 10,
      lift: { r: 0.05, g: 0.03, b: -0.01 },
      liftMaster: 0.04,
      gain: { r: 1.08, g: 1.04, b: 0.90 },
      shadowTint: { r: 0.16, g: 0.10, b: -0.04 },
      shadowTintStrength: 30,
      lutTitle: 'Wedding_Retro_Super8',
      lutDescription: 'Look nostalgic film Super 8 de nunta pentru DaVinci Resolve',
    },
  },
  {
    id: 'wedding-editorial-vogue',
    name: 'Nuntă Editorial Vogue (Glamour & High Fashion)',
    category: 'wedding',
    description: 'Stil de revistă de modă: contrast pronunțat de lux, alb pur fără tente galbene pe rochia de mireasă, negru adânc pe smoking și piele impecabilă.',
    previewColor: '#f43f5e',
    state: {
      contrast: 1.28,
      pivot: 0.44,
      temperature: -2,
      tint: 0,
      saturation: 1.06,
      colorBoost: 10,
      highlights: -10,
      whites: 4,
      shadows: -14,
      blacks: -8,
      lift: { r: -0.02, g: -0.01, b: 0.01 },
      gain: { r: 1.02, g: 1.01, b: 1.0 },
      masterCurve: [
        { x: 0, y: 0.0 },
        { x: 0.20, y: 0.12 },
        { x: 0.80, y: 0.88 },
        { x: 1, y: 1.0 },
      ],
      lutTitle: 'Wedding_Editorial_Vogue',
      lutDescription: 'Stil editorial de revista de moda de nunta pentru DaVinci Resolve',
    },
  },
  {
    id: 'wedding-church-ceremony',
    name: 'Nuntă Biserică & Vitralii (Sacred Candlelight)',
    category: 'wedding',
    description: 'Optimizat pentru cununii religioase în biserică: căldură solemnă de lumânare pe fețe, vitralii bogate și recuperare curată a detaliilor din umbrele reci.',
    previewColor: '#c084fc',
    state: {
      contrast: 1.16,
      pivot: 0.435,
      temperature: 8,
      tint: 1,
      saturation: 1.06,
      colorBoost: 14,
      highlights: -20,
      whites: -6,
      shadows: 8,
      blacks: -2,
      lift: { r: 0.01, g: 0.0, b: 0.02 },
      gamma: { r: 0.03, g: 0.01, b: -0.02 },
      gain: { r: 1.07, g: 1.02, b: 0.94 },
      highlightTint: { r: 0.18, g: 0.10, b: -0.08 },
      highlightTintStrength: 20,
      lutTitle: 'Wedding_Church_Sacred',
      lutDescription: 'Ambianta solemna de biserica cu lumanari pentru DaVinci Resolve',
    },
  },
  {
    id: 'wedding-sparkler-exit',
    name: 'Nuntă Sparkler Exit & Artificii de Noapte',
    category: 'wedding',
    description: 'Momentul artificiilor de mână (sparklers) și al artificiilor nocturne: protecție extremă pe canalele de alb pentru a reda detaliul fiecărei scântei și tenul luminat de flacără.',
    previewColor: '#fbbf24',
    state: {
      contrast: 1.26,
      pivot: 0.445,
      temperature: 6,
      tint: 2,
      saturation: 1.12,
      colorBoost: 15,
      highlights: -28,
      whites: -12,
      shadows: -12,
      blacks: -6,
      gain: { r: 1.05, g: 1.01, b: 0.95 },
      hueVsSat: { red: 8, yellow: 14, green: -10, cyan: -20, blue: -25, magenta: -15 },
      hueVsLum: { red: 10, yellow: 14, green: 0, cyan: -10, blue: -15, magenta: -10 },
      lutTitle: 'Wedding_Sparkler_Exit',
      lutDescription: 'Protectie scantei si artificii de noapte pentru DaVinci Resolve',
    },
  },
  // ==========================================
  // BALANSURI DE CULORI NATURALE PENTRU TOATE CAMERELE VIDEO
  // ==========================================
  // 1. PANASONIC LUMIX GH5 / GH5S
  {
    id: 'panasonic-gh5-wedding',
    name: 'Panasonic GH5 · Ton Natural Ten (Anti-Green)',
    category: 'camera_profile',
    description: 'Profil calibrat pentru senzorul Panasonic GH5: elimină nuanța verzuie tipică din umbre (+5 Tint), aliniază tenul pe spectrul roz-auriu și oferă contrast fin Rec.709 Gamma 2.4.',
    previewColor: '#0ea5e9',
    state: {
      inputSpace: 'panasonic_gh5',
      contrast: 1.14,
      pivot: 0.435,
      temperature: 4,
      tint: 5,
      saturation: 1.12,
      colorBoost: 12,
      highlights: -12,
      shadows: 4,
      lift: { r: 0.02, g: -0.03, b: 0.01 },
      gain: { r: 1.06, g: 1.0, b: 0.95 },
      hueVsHue: { red: 2, yellow: -4, green: 10, cyan: 0, blue: -4, magenta: 0 },
      hueVsSat: { red: 14, yellow: 8, green: -12, cyan: 0, blue: 4, magenta: -6 },
      lutTitle: 'Panasonic_GH5_Ten_Natural',
      lutDescription: 'Balans ten natural si corectie tenta verde Panasonic GH5 pentru DaVinci Resolve',
    },
  },
  {
    id: 'panasonic-gh5-daylight-natural',
    name: 'Panasonic GH5 · Soare Direct 5600K Neutru',
    category: 'camera_profile',
    description: 'Balans de zi 5600K pur pentru exterior GH5: cer albastru curat, rochie de mireasă albă imaculată și eliminarea devierilor spre galben/verzui.',
    previewColor: '#38bdf8',
    state: {
      inputSpace: 'panasonic_gh5',
      contrast: 1.10,
      pivot: 0.435,
      temperature: 1,
      tint: 3,
      saturation: 1.06,
      colorBoost: 8,
      highlights: -10,
      whites: -4,
      shadows: 2,
      gain: { r: 1.02, g: 1.0, b: 0.98 },
      lutTitle: 'Panasonic_GH5_Daylight_5600K',
      lutDescription: 'Balans lumina de zi exterior neutru Panasonic GH5 Rec.709',
    },
  },
  {
    id: 'panasonic-gh5-nature-grass',
    name: 'Panasonic GH5 · Cununie în Natură & Verdeață',
    category: 'camera_profile',
    description: 'Optimizat pentru cununii în aer liber: calmează saturația excesivă a ierbii de vară și îndepărtează reflexiile verzi de pe bărbia și obrajii mirilor.',
    previewColor: '#10b981',
    state: {
      inputSpace: 'panasonic_gh5',
      contrast: 1.12,
      pivot: 0.435,
      temperature: 5,
      tint: -2,
      saturation: 1.08,
      colorBoost: 10,
      highlights: -14,
      shadows: 4,
      hueVsSat: { red: 10, yellow: -8, green: -22, cyan: 4, blue: 6, magenta: -4 },
      lutTitle: 'Panasonic_GH5_Natura_Verde',
      lutDescription: 'Balans cununie natura iarba frunzis Panasonic GH5',
    },
  },
  {
    id: 'panasonic-gh5-church-ambient',
    name: 'Panasonic GH5 · Biserică & Lumânări / Vitralii',
    category: 'camera_profile',
    description: 'Echilibru solemn în interiorul bisericii: protejează flăcările lumânărilor și aurul iconostasului menținând tenul preotului și al mirilor curat.',
    previewColor: '#a855f7',
    state: {
      inputSpace: 'panasonic_gh5',
      contrast: 1.15,
      pivot: 0.435,
      temperature: -8,
      tint: 6,
      saturation: 1.05,
      colorBoost: 8,
      highlights: -18,
      shadows: 6,
      lutTitle: 'Panasonic_GH5_Biserica_Solemn',
      lutDescription: 'Balans biserica lumanari si vitralii Panasonic GH5',
    },
  },

  // 2. PANASONIC AG-UX90 (4K CAMCORDER)
  {
    id: 'panasonic-ux90-wedding',
    name: 'Panasonic UX90 · Ton Natural Catifelat (Soft Skintone)',
    category: 'camera_profile',
    description: 'Calibrare pentru Panasonic AG-UX90: temperează saturația aspră specifică senzorilor de cameră video broadcast, protejează rochia de mireasă și aduce tenul în tonuri naturale.',
    previewColor: '#6366f1',
    state: {
      inputSpace: 'panasonic_ux90',
      contrast: 1.08,
      pivot: 0.435,
      temperature: 2,
      tint: 2,
      saturation: 0.96,
      colorBoost: 6,
      highlights: -16,
      whites: -6,
      shadows: 6,
      gain: { r: 1.02, g: 0.99, b: 0.96 },
      hueVsSat: { red: -8, yellow: -10, green: -18, cyan: -5, blue: 0, magenta: -12 },
      lutTitle: 'Panasonic_UX90_Ten_Catifelat',
      lutDescription: 'Balans ten catifelat nunti Panasonic AG-UX90 Rec.709 Gamma 2.4',
    },
  },
  {
    id: 'panasonic-ux90-daylight-clean',
    name: 'Panasonic UX90 · Soare Direct 5600K Neutru',
    category: 'camera_profile',
    description: 'Lumină solară exterioară directă: coboară ușor saturația broadcast (-4%) pentru a elimina aspectul de cameră TV și oferă gamă dinamică plăcută.',
    previewColor: '#818cf8',
    state: {
      inputSpace: 'panasonic_ux90',
      contrast: 1.06,
      pivot: 0.435,
      temperature: 0,
      tint: 1,
      saturation: 0.96,
      colorBoost: 4,
      highlights: -14,
      shadows: 4,
      lutTitle: 'Panasonic_UX90_Daylight_5600K',
      lutDescription: 'Balans lumina de zi 5600K neutru Panasonic UX90',
    },
  },
  {
    id: 'panasonic-ux90-wedding-hall',
    name: 'Panasonic UX90 · Sală Nuntă & Lumini LED',
    category: 'camera_profile',
    description: 'Compensare pentru sala de mese și ringul de dans: temperează lămpile LED albastre și reflectoarele calde, menținând smokingul și decorul la niveluri naturale.',
    previewColor: '#4f46e5',
    state: {
      inputSpace: 'panasonic_ux90',
      contrast: 1.10,
      pivot: 0.435,
      temperature: -6,
      tint: -4,
      saturation: 0.94,
      colorBoost: 6,
      highlights: -18,
      whites: -8,
      shadows: 8,
      lutTitle: 'Panasonic_UX90_Sala_Nunta',
      lutDescription: 'Balans sala receptie si lumini LED Panasonic UX90',
    },
  },

  // 3. SONY FX30 / FX3 (S-LOG3 & S-CINETONE)
  {
    id: 'sony-fx30-wedding',
    name: 'Sony FX30 / FX3 · Ton Natural Ten (Anti-Olive)',
    category: 'camera_profile',
    description: 'Calibrare dedicată senzorului Sony FX30 / FX3: convertește S-Log3 în Rec.709 Gamma 2.4, curăță tenta gălbui-măslinie din tonurile medii și conferă tenului strălucire roz-aurie sănătoasă.',
    previewColor: '#ec4899',
    state: {
      inputSpace: 'sony_fx30',
      contrast: 1.15,
      pivot: 0.435,
      temperature: 3,
      tint: 2,
      saturation: 1.1,
      colorBoost: 12,
      highlights: -14,
      shadows: -2,
      lift: { r: 0.01, g: -0.01, b: 0.0 },
      gain: { r: 1.05, g: 1.01, b: 0.96 },
      hueVsHue: { red: 4, yellow: -6, green: 12, cyan: -4, blue: -2, magenta: 0 },
      hueVsSat: { red: 16, yellow: 10, green: -15, cyan: 5, blue: 8, magenta: -6 },
      lutTitle: 'Sony_FX30_Ten_Natural',
      lutDescription: 'Balans ten natural anti-olive Sony FX30/FX3 Rec.709 Gamma 2.4',
    },
  },
  {
    id: 'sony-fx30-daylight-5600k',
    name: 'Sony FX30 / FX3 · Soare Direct 5600K Neutru',
    category: 'camera_profile',
    description: 'Lumină solară pură de zi pentru Sony FX30: cer albastru bogat, alb neutru la rochia de mireasă și separare curată fără dominantă cromatică.',
    previewColor: '#f472b6',
    state: {
      inputSpace: 'sony_fx30',
      contrast: 1.12,
      pivot: 0.435,
      temperature: 0,
      tint: 1,
      saturation: 1.06,
      colorBoost: 8,
      highlights: -12,
      shadows: 0,
      gain: { r: 1.02, g: 1.0, b: 0.97 },
      lutTitle: 'Sony_FX30_Daylight_5600K',
      lutDescription: 'Balans neutru lumina soarelui Sony FX30/FX3',
    },
  },
  {
    id: 'sony-fx30-outdoor-nature',
    name: 'Sony FX30 / FX3 · Cununie în Natură & Verde Smarald',
    category: 'camera_profile',
    description: 'Corectează tendința senzorului Sony de a vira verdele spre galben-neon: transformă vegetația într-un verde smarald organic de peliculă de film.',
    previewColor: '#059669',
    state: {
      inputSpace: 'sony_fx30',
      contrast: 1.14,
      pivot: 0.435,
      temperature: 4,
      tint: -3,
      saturation: 1.08,
      colorBoost: 10,
      highlights: -16,
      shadows: 2,
      hueVsHue: { red: 2, yellow: -8, green: 16, cyan: -2, blue: 0, magenta: 0 },
      hueVsSat: { red: 12, yellow: -10, green: -20, cyan: 6, blue: 8, magenta: -4 },
      lutTitle: 'Sony_FX30_Natura_Smarald',
      lutDescription: 'Balans cununie natura verde smarald Sony FX30',
    },
  },
  {
    id: 'sony-fx30-golden-sunset',
    name: 'Sony FX30 / FX3 · Apus Cald / Tuscan Sunset',
    category: 'camera_profile',
    description: 'Ședință foto la apus (Golden Hour): radiază o căldură organică de chihlimbar și miere protejând textura rochiei și detaliile din părul miresei.',
    previewColor: '#f59e0b',
    state: {
      inputSpace: 'sony_fx30',
      contrast: 1.16,
      pivot: 0.435,
      temperature: 20,
      tint: 2,
      saturation: 1.14,
      colorBoost: 14,
      highlights: -20,
      shadows: -4,
      gain: { r: 1.08, g: 1.03, b: 0.94 },
      lutTitle: 'Sony_FX30_Apus_Auriu',
      lutDescription: 'Balans apus auriu Golden Hour Sony FX30/FX3',
    },
  },
  {
    id: 'sony-fx30-church-mixed',
    name: 'Sony FX30 / FX3 · Biserică & Candelabre Solemn',
    category: 'camera_profile',
    description: 'Cununie religioasă în biserică: elimină excesul de galben al lumânărilor menținând picturile murale și fețele mirilor la un nivel IRE natural.',
    previewColor: '#7c3aed',
    state: {
      inputSpace: 'sony_fx30',
      contrast: 1.18,
      pivot: 0.435,
      temperature: -10,
      tint: 4,
      saturation: 1.06,
      colorBoost: 8,
      highlights: -18,
      shadows: 4,
      lutTitle: 'Sony_FX30_Biserica_Solemn',
      lutDescription: 'Balans cununie biserica lumanari Sony FX30',
    },
  },

  // 4. CANON EOS R6 / R6 MARK II (C-LOG3)
  {
    id: 'canon-r6-wedding',
    name: 'Canon R6 · Ton Natural Piele (Canon Skintone Magic)',
    category: 'camera_profile',
    description: 'Calibrare pentru Canon EOS R6 & R6 Mark II: valorifică fidelitatea legendară Canon pe ten, stabilizând roșul sub luminile intense ale sălii de nuntă.',
    previewColor: '#ef4444',
    state: {
      inputSpace: 'canon_r6',
      contrast: 1.12,
      pivot: 0.435,
      temperature: 2,
      tint: -1,
      saturation: 1.08,
      colorBoost: 8,
      highlights: -15,
      whites: -4,
      shadows: 2,
      gain: { r: 1.03, g: 1.01, b: 0.97 },
      hueVsHue: { red: 2, yellow: -4, green: 8, cyan: 0, blue: -2, magenta: -2 },
      hueVsSat: { red: 8, yellow: 12, green: -20, cyan: -5, blue: 5, magenta: -10 },
      lutTitle: 'Canon_R6_Ten_Natural',
      lutDescription: 'Balans C-Log3 Canon R6 ten natural Rec.709 Gamma 2.4',
    },
  },
  {
    id: 'canon-r6-daylight-neutral',
    name: 'Canon R6 · Soare Direct 5600K Clasic',
    category: 'camera_profile',
    description: 'Balans neutru de exterior pentru Canon C-Log3: cer adânc, detalii cristaline în voalul miresei și nuanțe cromatice echilibrate 1:1.',
    previewColor: '#f87171',
    state: {
      inputSpace: 'canon_r6',
      contrast: 1.10,
      pivot: 0.435,
      temperature: 0,
      tint: -1,
      saturation: 1.06,
      colorBoost: 6,
      highlights: -12,
      shadows: 0,
      gain: { r: 1.01, g: 1.0, b: 0.98 },
      lutTitle: 'Canon_R6_Daylight_5600K',
      lutDescription: 'Balans lumina zi exterior Canon EOS R6 C-Log3',
    },
  },
  {
    id: 'canon-r6-garden-wedding',
    name: 'Canon R6 · Grădină & Frunziș Echilibrat',
    category: 'camera_profile',
    description: 'Cadre în parc sau grădină botanică: temperează tenta galbenă din frunze și păstrează tenul mirilor radiant fără nicio reflexie nedorită.',
    previewColor: '#047857',
    state: {
      inputSpace: 'canon_r6',
      contrast: 1.12,
      pivot: 0.435,
      temperature: 3,
      tint: -4,
      saturation: 1.06,
      colorBoost: 8,
      highlights: -16,
      shadows: 2,
      hueVsSat: { red: 6, yellow: -6, green: -24, cyan: 4, blue: 4, magenta: -6 },
      lutTitle: 'Canon_R6_Gradina_Verde',
      lutDescription: 'Balans gradina si frunzis cununie Canon R6',
    },
  },
  {
    id: 'canon-r6-golden-hour',
    name: 'Canon R6 · Apus Auriu & Voal Mătăsos',
    category: 'camera_profile',
    description: 'Golden Hour la apus: scaldă rochia și fețele într-o lumină caldă de poveste, cu separare optimă a fundalului și contrast catifelat.',
    previewColor: '#d97706',
    state: {
      inputSpace: 'canon_r6',
      contrast: 1.14,
      pivot: 0.435,
      temperature: 18,
      tint: 0,
      saturation: 1.12,
      colorBoost: 12,
      highlights: -18,
      shadows: -2,
      gain: { r: 1.06, g: 1.02, b: 0.95 },
      lutTitle: 'Canon_R6_Apus_Auriu',
      lutDescription: 'Balans apus de soare auriu Canon R6',
    },
  },
  {
    id: 'canon-r6-church-hall',
    name: 'Canon R6 · Biserică & Sală Lumini Calde',
    category: 'camera_profile',
    description: 'Interior cu candelabre și lumânări: neutralizează roșeața excesivă sub reflectoare halogen, păstrând atmosfera sacră a momentului.',
    previewColor: '#9333ea',
    state: {
      inputSpace: 'canon_r6',
      contrast: 1.15,
      pivot: 0.435,
      temperature: -8,
      tint: 1,
      saturation: 1.04,
      colorBoost: 6,
      highlights: -16,
      shadows: 4,
      lutTitle: 'Canon_R6_Biserica_Sala',
      lutDescription: 'Balans interior biserica si sala lumini calde Canon R6',
    },
  },

  // 5. BLACKMAGIC BMPCC (POCKET 4K / 6K GEN 5)
  {
    id: 'bmpcc-wedding-skintone',
    name: 'BMPCC Gen 5 · Ton Piele Film Kodak 10:30',
    category: 'camera_profile',
    description: 'Blackmagic Generation 5 Color Science: ten organic tip peliculă Kodak Vision3, cu treceri extrem de line în zonele de umbră.',
    previewColor: '#f97316',
    state: {
      inputSpace: 'bmdgen5',
      contrast: 1.16,
      pivot: 0.435,
      temperature: 2,
      tint: 1,
      saturation: 1.10,
      colorBoost: 10,
      highlights: -16,
      shadows: 2,
      gain: { r: 1.04, g: 1.01, b: 0.96 },
      lutTitle: 'BMPCC_Gen5_Ten_Film',
      lutDescription: 'Balans ten film Kodak Blackmagic BMPCC Gen 5 Rec.709',
    },
  },
  {
    id: 'bmpcc-daylight-natural',
    name: 'BMPCC Gen 5 · Soare Direct 5600K Film Neutru',
    category: 'camera_profile',
    description: 'Balans de zi exterior pentru Blackmagic RAW / Gen 5: roll-off catifelat pe rochia de mireasă, fără artefacte digitale pe cer.',
    previewColor: '#fb923c',
    state: {
      inputSpace: 'bmdgen5',
      contrast: 1.12,
      pivot: 0.435,
      temperature: 0,
      tint: 0,
      saturation: 1.08,
      colorBoost: 6,
      highlights: -14,
      shadows: 0,
      lutTitle: 'BMPCC_Gen5_Daylight_5600K',
      lutDescription: 'Balans soare direct exterior Blackmagic BMPCC Gen 5',
    },
  },
  {
    id: 'bmpcc-forest-nature',
    name: 'BMPCC Gen 5 · Cununie în Pădure & Natură',
    category: 'camera_profile',
    description: 'Cununie în pădure: nuanțe bogate de verde smarald și pământ ars, ten protejat și contrast bogat fără umbre zdrobite.',
    previewColor: '#15803d',
    state: {
      inputSpace: 'bmdgen5',
      contrast: 1.14,
      pivot: 0.435,
      temperature: 4,
      tint: -4,
      saturation: 1.10,
      colorBoost: 8,
      highlights: -16,
      shadows: 4,
      hueVsSat: { red: 8, yellow: -8, green: -20, cyan: 2, blue: 4, magenta: -4 },
      lutTitle: 'BMPCC_Gen5_Padure_Natura',
      lutDescription: 'Balans padure si natura verde Blackmagic BMPCC Gen 5',
    },
  },
];

// Helper to construct a complete grading state from a preset
export function applyPresetToState(baseState: GradingState, preset: LutPreset): GradingState {
  return {
    ...DEFAULT_GRADING_STATE,
    lutTitle: preset.state.lutTitle || preset.name.replace(/[^a-zA-Z0-9_]/g, '_'),
    lutDescription: preset.description,
    ...preset.state,
    // Preserve custom titles if already set
    lutCreator: baseState.lutCreator,
  };
}
